#!/usr/bin/env python3
"""Generate ThemeGalleryData.swift from Apollo-Reborn's portable theme JSON.

Apollo-Reborn ships its gallery as 50 schema-v3 JSON files under
theme-gallery/themes/, with a generator that emits an ObjC table
(theme-gallery/scripts/generate_catalog.py). The JSON is the portable
format and the ObjC is just one backend, so this reads the SAME JSON
and emits Swift - the colours are upstream's, unmodified.

The validation below is upstream's, ported one-for-one, so a malformed
or renamed theme fails here exactly as it would fail there.

Usage: gen-theme-gallery.py <themes dir> <output.swift>
"""

import json
import re
import sys
from pathlib import Path

# Key list and validation follow Reborn's theme catalog generator.
INPUT_KEYS = ["accent", "background", "card", "raised", "bars", "text", "mutedText", "separator"]
MODES = ["light", "dark"]
HEX_RE = re.compile(r"^[0-9A-Fa-f]{6}$")
VARIANTS = {"subtle", "balanced", "bold"}


def fail(path, message):
    raise SystemExit(f"{path}: {message}")


def load_theme(path):
    try:
        data = json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        fail(path, f"invalid JSON: {exc}")

    slug = path.stem
    # Slugs are persisted in user backups; renaming a shipped slug orphans
    # restores.
    if data.get("schemaVersion") != 3:
        fail(path, "schemaVersion must be 3")
    if data.get("slug") != slug:
        fail(path, f"slug must match filename stem ({slug})")
    if not isinstance(data.get("name"), str) or not data["name"].strip():
        fail(path, "name must be a non-empty string")
    if data.get("variant") not in VARIANTS:
        fail(path, "variant must be subtle, balanced, or bold")
    if data.get("advancedEnabled") is not True:
        fail(path, "advancedEnabled must be true")

    input_obj = data.get("input")
    if not isinstance(input_obj, dict):
        fail(path, "input must be an object")
    for mode in MODES:
        mode_obj = input_obj.get(mode)
        if not isinstance(mode_obj, dict):
            fail(path, f"input.{mode} must be an object")
        for key in INPUT_KEYS:
            value = mode_obj.get(key)
            if not isinstance(value, str) or not HEX_RE.match(value):
                fail(path, f"input.{mode}.{key} must be exactly 6 hex digits")
            mode_obj[key] = value.upper()

    return {"slug": slug, "name": data["name"], "variant": data["variant"], "input": input_obj}


def swift_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main(themes_dir, out_path):
    paths = sorted(Path(themes_dir).glob("*.json"))
    if not paths:
        raise SystemExit(f"{themes_dir}: no theme JSON found")
    themes = [load_theme(p) for p in paths]

    slugs = [t["slug"] for t in themes]
    if len(set(slugs)) != len(slugs):
        raise SystemExit("duplicate slugs")

    lines = [
        "// GENERATED by scripts/generate/gen-theme-gallery.py - do not edit by hand.",
        "//",
        "// Ported from Apollo-Reborn's portable schema-v3 theme JSON. Every hex",
        "// below is upstream's, unmodified. Slugs are persisted in user backups, so",
        "// renaming one orphans restores.",
        "",
        "public extension ThemeGallery {",
        f"    /// All {len(themes)} gallery themes, in slug order.",
        "    static let all: [GalleryTheme] = [",
    ]
    for t in themes:
        lines.append("        GalleryTheme(")
        lines.append(f"            slug: {swift_str(t['slug'])},")
        lines.append(f"            name: {swift_str(t['name'])},")
        lines.append(f"            variant: .{t['variant']},")
        lines.append("            input: [")
        for mode in MODES:
            lines.append(f"                .{mode}: [")
            for key in INPUT_KEYS:
                lines.append(f"                    .{key}: {swift_str(t['input'][mode][key])},")
            lines.append("                ],")
        lines.append("            ]")
        lines.append("        ),")
    lines += ["    ]", "}", ""]
    Path(out_path).write_text("\n".join(lines))
    print(f"{len(themes)} themes -> {out_path}")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
