import Foundation

/// Apollo's named accent-colour themes (18, each with an independent
/// light/dark toggle) and named comment-depth palettes (Blep, Combustion,
/// Forest, Nuit, Ocean, Rainbow, each with Light/Dark 7-colour hex arrays).
/// A `Theme` pairs one accent theme with one palette; Apollo lets the two
/// vary independently.
public struct Theme: Codable, Sendable, Equatable, Identifiable {
    public var id: String
    public var name: String
    /// Hex string like "FF6B35", applied via `.tint()` across the app.
    public var accentColorHex: String
    /// Colors cycled through by comment depth (root, then each reply
    /// level) for the left-edge depth indicator.
    public var commentDepthColorHexes: [String]
    /// Which named `CommentColorPalette` this theme pairs with. Stored
    /// so the real "Comments Theme" row can show the theme's own
    /// palette name when no override is set, and so an override can be
    /// expressed as a palette NAME rather than a copy of its hexes
    /// (which would silently go stale against the palette data).
    /// Optional: themes generated by AI or imported via QR carry custom
    /// hexes with no named palette.
    public var commentPaletteName: String?
    /// Whether this variant targets dark appearance. Two themes with
    /// the same `name` but different `isDark` form a real light/dark
    /// pair, matching Apollo's actual theme structure.
    public var isDark: Bool
    /// `true` for a theme generated via `ThemeGenerationClient` (AI)
    /// or imported via QR code, rather than one of the bundled
    /// built-ins — used by the UI to group/label them separately.
    public var isGenerated: Bool
    /// "Colourize Vote Arrows": idle arrows use the accent colour, but
    /// a cast vote still shows Apollo's green/blue, since that pairing
    /// is the "you voted this way" signal and forcing both to the same
    /// accent would erase it.
    public var voteArrowsAccent: Bool

    public init(id: String, name: String, accentColorHex: String, commentDepthColorHexes: [String], isDark: Bool = false, isGenerated: Bool = false, commentPaletteName: String? = nil, voteArrowsAccent: Bool = false) {
        self.id = id
        self.name = name
        self.accentColorHex = accentColorHex
        self.commentDepthColorHexes = commentDepthColorHexes
        self.isDark = isDark
        self.isGenerated = isGenerated
        self.commentPaletteName = commentPaletteName
        self.voteArrowsAccent = voteArrowsAccent
    }

    /// Custom decode so themes persisted before `isDark`/`isGenerated`
    /// existed still decode successfully.
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(String.self, forKey: .id)
        name = try container.decode(String.self, forKey: .name)
        accentColorHex = try container.decode(String.self, forKey: .accentColorHex)
        commentDepthColorHexes = try container.decode([String].self, forKey: .commentDepthColorHexes)
        isDark = try container.decodeIfPresent(Bool.self, forKey: .isDark) ?? false
        isGenerated = try container.decodeIfPresent(Bool.self, forKey: .isGenerated) ?? false
        // Absent-tolerant: older persisted themes carry no palette name. `nil`
        // means "this theme's own custom hexes", which `CommentsThemeStore`
        // handles rather than falling back to Rainbow.
        commentPaletteName = try container.decodeIfPresent(String.self, forKey: .commentPaletteName)
        // Absent-tolerant like the fields above: defaults to off.
        voteArrowsAccent = try container.decodeIfPresent(Bool.self, forKey: .voteArrowsAccent) ?? false
    }

    private init(realName: String, accentColorHex: String, palette: String, isDark: Bool) {
        let variant = isDark ? "Dark" : "Light"
        self.id = "\(realName.lowercased().replacingOccurrences(of: " ", with: "_"))_\(variant.lowercased())"
        self.name = realName
        self.accentColorHex = accentColorHex
        self.commentDepthColorHexes = CommentColorPalette.hexes(named: palette, isDark: isDark)
        self.commentPaletteName = palette
        self.isDark = isDark
        self.isGenerated = false
        self.voteArrowsAccent = false
    }

    // MARK: - The real, complete 18-theme accent catalog
    // Accents follow Reborn's built-in theme table, light and dark. Every
    // built-in theme uses Rainbow comment colours, Apollo's one default; the
    // palette is chosen separately (Comments Theme).

    public static let defaultLight = Theme(realName: "Default", accentColorHex: "007AFF", palette: "Rainbow", isDark: false)
    public static let defaultDark = Theme(realName: "Default", accentColorHex: "2399FF", palette: "Rainbow", isDark: true)
    public static let nefertitiLight = Theme(realName: "Nefertiti", accentColorHex: "01A200", palette: "Rainbow", isDark: false)
    public static let nefertitiDark = Theme(realName: "Nefertiti", accentColorHex: "01A200", palette: "Rainbow", isDark: true)
    public static let fieryStareLight = Theme(realName: "Fiery Stare", accentColorHex: "FF0000", palette: "Rainbow", isDark: false)
    public static let fieryStareDark = Theme(realName: "Fiery Stare", accentColorHex: "FD0000", palette: "Rainbow", isDark: true)
    public static let spookyPumpkinLight = Theme(realName: "Spooky Pumpkin", accentColorHex: "FF6200", palette: "Rainbow", isDark: false)
    public static let spookyPumpkinDark = Theme(realName: "Spooky Pumpkin", accentColorHex: "F25D00", palette: "Rainbow", isDark: true)
    public static let solarizedLight = Theme(realName: "Solarized", accentColorHex: "268BD2", palette: "Rainbow", isDark: false)
    public static let solarizedDark = Theme(realName: "Solarized", accentColorHex: "268BD2", palette: "Rainbow", isDark: true)
    public static let outrunLight = Theme(realName: "Outrun", accentColorHex: "C400A6", palette: "Rainbow", isDark: false)
    public static let outrunDark = Theme(realName: "Outrun", accentColorHex: "FF00D8", palette: "Rainbow", isDark: true)
    public static let sunsetLight = Theme(realName: "Sunset", accentColorHex: "FF6600", palette: "Rainbow", isDark: false)
    public static let sunsetDark = Theme(realName: "Sunset", accentColorHex: "FF7D00", palette: "Rainbow", isDark: true)
    public static let sepiaLight = Theme(realName: "Sepia", accentColorHex: "B88023", palette: "Rainbow", isDark: false)
    public static let sepiaDark = Theme(realName: "Sepia", accentColorHex: "D3AC72", palette: "Rainbow", isDark: true)
    public static let monochromaticLight = Theme(realName: "Monochromatic", accentColorHex: "000000", palette: "Rainbow", isDark: false)
    public static let monochromaticDark = Theme(realName: "Monochromatic", accentColorHex: "FFFFFF", palette: "Rainbow", isDark: true)
    public static let navyLight = Theme(realName: "Navy", accentColorHex: "0058B8", palette: "Rainbow", isDark: false)
    public static let navyDark = Theme(realName: "Navy", accentColorHex: "0060C9", palette: "Rainbow", isDark: true)
    public static let skiesOnSkiesLight = Theme(realName: "Skies on Skies", accentColorHex: "00B5F2", palette: "Rainbow", isDark: false)
    public static let skiesOnSkiesDark = Theme(realName: "Skies on Skies", accentColorHex: "01ADE8", palette: "Rainbow", isDark: true)
    public static let majesticPurpleLight = Theme(realName: "Majestic Purple", accentColorHex: "8800FF", palette: "Rainbow", isDark: false)
    public static let majesticPurpleDark = Theme(realName: "Majestic Purple", accentColorHex: "9C2CFF", palette: "Rainbow", isDark: true)
    public static let magentasplosionLight = Theme(realName: "Magentasplosion", accentColorHex: "FF00B2", palette: "Rainbow", isDark: false)
    public static let magentasplosionDark = Theme(realName: "Magentasplosion", accentColorHex: "E800A2", palette: "Rainbow", isDark: true)
    public static let sniffingWalnutLight = Theme(realName: "Sniffing Walnut", accentColorHex: "A74E00", palette: "Rainbow", isDark: false)
    public static let sniffingWalnutDark = Theme(realName: "Sniffing Walnut", accentColorHex: "A74E00", palette: "Rainbow", isDark: true)
    public static let fisherKingLight = Theme(realName: "Fisher King", accentColorHex: "808286", palette: "Rainbow", isDark: false)
    public static let fisherKingDark = Theme(realName: "Fisher King", accentColorHex: "76787D", palette: "Rainbow", isDark: true)
    public static let chumbusLight = Theme(realName: "Chumbus", accentColorHex: "F8F8F8", palette: "Rainbow", isDark: false)
    public static let chumbusDark = Theme(realName: "Chumbus", accentColorHex: "20242B", palette: "Rainbow", isDark: true)
    public static let draculaLight = Theme(realName: "Dracula", accentColorHex: "9760FF", palette: "Rainbow", isDark: false)
    public static let draculaDark = Theme(realName: "Dracula", accentColorHex: "AD81FF", palette: "Rainbow", isDark: true)
    public static let mintLight = Theme(realName: "Mint", accentColorHex: "37BB98", palette: "Rainbow", isDark: false)
    public static let mintDark = Theme(realName: "Mint", accentColorHex: "62DFA7", palette: "Rainbow", isDark: true)

    /// The full 18-theme catalog (36 entries counting light/dark pairs).
    public static let allThemes: [Theme] = [
        .defaultLight, .defaultDark,
        .nefertitiLight, .nefertitiDark,
        .fieryStareLight, .fieryStareDark,
        .spookyPumpkinLight, .spookyPumpkinDark,
        .solarizedLight, .solarizedDark,
        .outrunLight, .outrunDark,
        .sunsetLight, .sunsetDark,
        .sepiaLight, .sepiaDark,
        .monochromaticLight, .monochromaticDark,
        .navyLight, .navyDark,
        .skiesOnSkiesLight, .skiesOnSkiesDark,
        .majesticPurpleLight, .majesticPurpleDark,
        .magentasplosionLight, .magentasplosionDark,
        .sniffingWalnutLight, .sniffingWalnutDark,
        .fisherKingLight, .fisherKingDark,
        .chumbusLight, .chumbusDark,
        .draculaLight, .draculaDark,
        .mintLight, .mintDark,
    ]
}

/// Apollo's comment-color-depth palettes: 6 named palettes, each with
/// `Light`/`Dark` 7-color hex arrays.
public enum CommentColorPalette {
    public static let all: [String: [Bool: [String]]] = [
        "Blep": [
            false: ["F75943", "4F8DDE", "967DDA", "F5BB4F", "30AD63", "FF8800", "FF3636"],
            true: ["AF483C", "3F6AA4", "6F60A1", "AE8944", "2A8051", "B5670F", "9F2025"],
        ],
        "Combustion": [
            false: ["FF0000", "D30000", "CF5D00", "FF7D00", "EFA309", "F7C804", "F7C804"],
            true: ["BC0B0D", "9C0B0D", "A2350E", "BC630D", "B07D13", "A6940F", "99A10E"],
        ],
        "Forest": [
            false: ["274F35", "55713C", "318F29", "97CB6D", "A8BF65", "6BD262", "908F36"],
            true: ["274F35", "55713C", "318F29", "739959", "8E902D", "549E52", "6E6F33"],
        ],
        "Nuit": [
            false: ["000000", "1D1E21", "303135", "43454A", "5B5E63", "73767D", "8A8E97"],
            true: ["2C3038", "35383F", "313338", "42454A", "52555C", "65676E", "7B7E85"],
        ],
        "Ocean": [
            false: ["0370C1", "008FFB", "00C3F9", "008FFB", "24A1FF", "007AD5", "78B5FF"],
            true: ["005495", "0675C4", "178DB1", "0374CD", "3879AB", "0B5B9A", "436DA4"],
        ],
        "Rainbow": [
            false: ["F24336", "FF922E", "F9D141", "2D704C", "0D74DC", "224688", "643B95"],
            true: ["AF2E27", "B15610", "967727", "2D704C", "1F68B1", "224688", "643B95"],
        ],
    ]

    public static func hexes(named palette: String, isDark: Bool) -> [String] {
        all[palette]?[isDark] ?? all["Rainbow"]![isDark]!
    }

    /// Apollo's palette order.
    public static let names: [String] = ["Rainbow", "Combustion", "Ocean", "Forest", "Nuit", "Blep"]
}

/// The "Comments Theme" row (Settings > Appearance > Theme Manager >
/// Options). Apollo keeps the comments palette separate from the accent
/// theme, so any pairing is possible. `nil` follows the selected theme's
/// own palette.
public enum CommentsThemeStore {
    private static let key = "com.pendo324.Phoebus.commentsThemePalette"

    /// The user's explicit palette override, or `nil` to follow the theme.
    public static var overridePaletteName: String? {
        get {
            guard let name = UserDefaults.standard.string(forKey: key),
                  CommentColorPalette.all[name] != nil else { return nil }
            return name
        }
        set {
            if let newValue, CommentColorPalette.all[newValue] != nil {
                UserDefaults.standard.set(newValue, forKey: key)
            } else {
                UserDefaults.standard.removeObject(forKey: key)
            }
        }
    }

    /// The palette name actually in effect: the override when set,
    /// otherwise the active theme's own palette.
    public static func effectivePaletteName(theme: Theme) -> String {
        overridePaletteName ?? theme.commentPaletteName ?? "Rainbow"
    }

    /// The depth colours to render comment indent bars with, honouring
    /// both the override and the theme's light/dark variant.
    public static func effectiveHexes(theme: Theme) -> [String] {
        // With no override, a generated/imported theme keeps its OWN
        // custom hexes - it has no named palette to look up, and
        // falling back to Rainbow would silently discard the colours
        // the user generated or imported.
        if let override = overridePaletteName {
            return CommentColorPalette.hexes(named: override, isDark: theme.isDark)
        }
        if theme.commentPaletteName == nil, !theme.commentDepthColorHexes.isEmpty {
            return theme.commentDepthColorHexes
        }
        return CommentColorPalette.hexes(named: effectivePaletteName(theme: theme), isDark: theme.isDark)
    }
}

public enum ThemeStore {
    private static let key = "com.pendo324.Phoebus.selectedThemeID"
    private static let generatedKey = "com.pendo324.Phoebus.generatedThemes"

    /// Per-theme "Colourize Vote Arrows", stored by theme ID rather than
    /// on the theme itself: `save` only persists the selected theme's
    /// ID and rebuilds the rest from the fixed catalog, so a flag on a
    /// built-in theme would otherwise be discarded on the next `load`.
    private static let voteArrowsAccentKey =
        "com.pendo324.Phoebus.themeVoteArrowsAccent"

    private static func voteArrowsAccentMap() -> [String: Bool] {
        UserDefaults.standard.dictionary(forKey: voteArrowsAccentKey) as? [String: Bool] ?? [:]
    }

    public static func load() -> Theme {
        guard let id = UserDefaults.standard.string(forKey: key),
              var theme = allAvailableThemes().first(where: { $0.id == id }) else {
            return .defaultLight
        }
        // A custom theme carries its own vote-arrow choice.
        if CustomTheme.parse(themeID: id) == nil {
            theme.voteArrowsAccent = voteArrowsAccentMap()[id] ?? false
        }
        return theme
    }

    /// Posted whenever the selected theme changes so live views re-render; a
    /// plain `UserDefaults` write is invisible to SwiftUI.
    public static let didChangeNotification = Notification.Name("com.pendo324.Phoebus.themeDidChange")

    public static func save(_ theme: Theme) {
        UserDefaults.standard.set(theme.id, forKey: key)
        var accents = voteArrowsAccentMap()
        accents[theme.id] = theme.voteArrowsAccent
        UserDefaults.standard.set(accents, forKey: voteArrowsAccentKey)
        defer { NotificationCenter.default.post(name: didChangeNotification, object: nil) }
        // Persist generated (AI/imported) themes so they survive
        // relaunch and reappear in the picker, unlike the fixed
        // built-in catalog.
        // Custom themes live in `CustomThemeStore`, not this list.
        if theme.isGenerated, CustomTheme.parse(themeID: theme.id) == nil {
            addGeneratedTheme(theme)
        }
    }

    /// All themes selectable in the UI: the fixed built-in gallery
    /// plus any AI-generated or QR-imported themes the user has kept.
    public static func allAvailableThemes() -> [Theme] {
        Theme.allThemes + loadGeneratedThemes() + CustomThemeStore.bridgedThemes()
    }

    public static func loadGeneratedThemes() -> [Theme] {
        // Decoded per theme so one unreadable entry doesn't lose the rest.
        guard let data = UserDefaults.standard.data(forKey: generatedKey),
              let themes = try? JSONDecoder().decode(LossyArray<Theme>.self, from: data) else {
            return []
        }
        return themes.elements
    }

    public static func addGeneratedTheme(_ theme: Theme) {
        var themes = loadGeneratedThemes().filter { $0.id != theme.id }
        themes.append(theme)
        saveGeneratedThemes(themes)
    }

    public static func removeGeneratedTheme(id: String) {
        let themes = loadGeneratedThemes().filter { $0.id != id }
        saveGeneratedThemes(themes)
    }

    private static func saveGeneratedThemes(_ themes: [Theme]) {
        guard let data = try? JSONEncoder().encode(themes) else { return }
        UserDefaults.standard.set(data, forKey: generatedKey)
    }
}
