#!/usr/bin/env python3
"""Writes a target's Metadata.appintents on Linux, in place of Apple's
appintentsmetadataprocessor (macOS only).

Usage:
  scripts/appintents-metadata.py <out/Metadata.appintents> <file.swiftconstvalues>...
  scripts/appintents-metadata.py --self-test
  scripts/appintents-metadata.py --compare <fixtures dir>

iOS reads this metadata to find a bundle's App Intents: without it the
widget's configurable widgets get no settings (CHSErrorDomain 1103), and
the app's intents and App Shortcuts don't appear in Shortcuts, Siri or
Spotlight. The input is the compiler's const values for the target
(-emit-const-values, see Package.swift), which already hold what the
metadata needs: each type's mangled name, its conformances, availability,
and the literal titles, defaults, cases and phrases.

Only what Phoebus uses is supported:
- WidgetConfigurationIntents, and AppIntents whose perform() returns a
  result (plain, or with a dialog, a snippet, a snippet intent, or a
  String / [entity] value), with literal titles and descriptions
  (search keywords included), `supportedModes` and `isDiscoverable`, and
  the system intents OpenIntent, ShowInAppSearchResultsIntent (the
  `.general` scope) and SnippetIntent, declared as the assistant schemas
  `system.open` and `system.searchInApp` (`__appSchemaIntent`, what
  @AppIntent(schema:) expands to; the macro plugin only ships with Xcode,
  so the sources write the expansion out) or not;
- parameters that are String, [String], Bool, a String-backed AppEnum,
  an AppEntity of the target or a StringSearchCriteria (which may have no
  title), with literal defaults, and a Summary("...") showing every
  parameter;
- AppEntity and IndexedEntity types with literal display representations
  (a name, or name, numeric format and synonyms), @Property values of
  String, Int, Bool, Date and URL (with an indexing key), @DeferredProperty
  arrays of those or of the target's entities, and a Transferable URL /
  plain-text export, each with an EntityStringQuery (IndexedEntityQuery
  included);
- one AppShortcutsProvider with AppShortcut(intent:phrases:shortTitle:
  systemImageName:) entries whose phrases interpolate only the app name.
Anything else is an error rather than a guess, since iOS ignores or
rejects metadata it cannot match to the binary.

--self-test runs the generator on each Tests/Fixtures/AppIntents/<target>/
input.swiftconstvalues and compares the result with the output of Apple's
processor for the same input (Metadata.appintents next to it), then checks
that changes to the const values it cannot match to Apple's output are
refused. --compare does the comparison for any directory laid out like
that; the App Intents reference workflow runs it on fresh output from
Xcode 27. When a target's intents change, its fixture is regenerated by
that workflow (see docs/building-on-linux.md, "AppIntents metadata"); until
then the generator has not been verified for the new input.
Tests/Fixtures/AppIntents/Probe is Apple's output for the assistant schema
macros and deferred properties, from Tests/AppIntentsMacroProbe.
"""
import copy
import json
import sys
from pathlib import Path

TOOLS_VERSION = "27A266a"  # Xcode 27.0's appintentsmetadataprocessor, whose format this follows
WIDGET_CONFIGURATION = "com.apple.link.systemProtocol.WidgetConfiguration"
OPEN_ENTITY = "com.apple.link.systemProtocol.OpenEntity"
SHOW_IN_APP_SEARCH = "com.apple.link.systemProtocol.ShowInAppStringSearchResults"
SNIPPET = "com.apple.link.systemProtocol.Snippet"
ASSISTANT_INTENT = "com.apple.link.systemProtocol.AssistantIntent"
INDEXED_ENTITY = "com.apple.appintents.entity.Indexed"
# The value-type identifiers of a primitive, by Swift type.
PRIMITIVES = {"Swift.String": 0, "Swift.Bool": 1, "Swift.Int": 2, "Foundation.Date": 8, "Foundation.URL": 11}
STRING, BOOL = PRIMITIVES["Swift.String"], PRIMITIVES["Swift.Bool"]
# Content types of what a Transferable entity exports, by what it is exported as.
EXPORTED_URL = "public.url"
EXPORTED_PLAIN_TEXT = {"plainText": "public.plain-text"}
# The assistant schemas an intent may declare with `__appSchemaIntent` (what
# @AppIntent(schema:) expands to), as Apple names them in
# assistantDefinedSchemas, with the system intent each goes with.
ASSISTANT_SCHEMAS = {
    "system.open": ("OpenIntent", "AppIntents.OpenIntent"),
    "system.searchInApp": ("SystemSearchInAppIntent", "AppIntents.ShowInAppSearchResultsIntent"),
}


class Unsupported(Exception):
    pass


def text(key):
    return {"alternatives": [], "key": key}


def primitive(type_id):
    return {"primitive": {"wrapper": {"typeIdentifier": type_id}}}


def availability(entry):
    """The type's own @available(iOS ...), as Apple writes it: nothing but
    the wildcard for a type without one."""
    annotations = {"LNPlatformNameWildcard": {"introducedVersion": "*"}}
    for attr in entry.get("availabilityAttributes") or []:
        if attr.get("platform") == "iOS" and not attr.get("isUnavailable") and attr.get("introducedVersion"):
            annotations["LNPlatformNameIOS"] = {"introducedVersion": attr["introducedVersion"]}
    return annotations


def literal(value, what):
    """The string of a RawLiteral, or of an InitCall's first argument
    (IntentDescription("..."), TypeDisplayRepresentation(name: "..."))."""
    if value.get("valueKind") == "RawLiteral":
        return value["value"]
    if value.get("valueKind") == "InitCall":
        args = value["value"]["arguments"]
        if args and args[0].get("valueKind") == "RawLiteral":
            for extra in args[1:]:
                if extra.get("valueKind") not in ("NilLiteral", None):
                    raise Unsupported(f"{what}: argument {extra.get('label')} is not supported")
            return args[0]["value"]
    raise Unsupported(f"{what}: expected a string literal, got {value.get('valueKind')}")


def static_property(entry, label):
    return next((p for p in entry.get("properties", []) if p["label"] == label and p["isStatic"] == "true"), None)


def short_name(type_name):
    return type_name.rsplit(".", 1)[-1]


def build_enum(entry):
    name = entry["typeName"]
    raw = next((a["substitutedTypeName"] for a in entry.get("associatedTypeAliases", [])
                if a["typeAliasName"] == "RawValue"), None)
    if raw != "Swift.String":
        raise Unsupported(f"{name}: only String-backed AppEnums are supported (RawValue {raw})")

    type_display = static_property(entry, "typeDisplayRepresentation")
    if type_display is None:
        raise Unsupported(f"{name}: no literal typeDisplayRepresentation")
    display_name = literal(type_display, f"{name}.typeDisplayRepresentation")

    titles = {}
    cases_display = static_property(entry, "caseDisplayRepresentations")
    if cases_display is None or cases_display.get("valueKind") != "Dictionary":
        raise Unsupported(f"{name}: no literal caseDisplayRepresentations")
    for pair in cases_display["value"]:
        if pair["key"].get("valueKind") != "Enum":
            raise Unsupported(f"{name}: caseDisplayRepresentations keys must be cases")
        titles[pair["key"]["value"]["name"]] = literal(pair["value"], f"{name}.{pair['key']['value']['name']}")

    cases = []
    for case in entry.get("cases", []):
        if case["name"] not in titles:
            raise Unsupported(f"{name}.{case['name']}: no display representation")
        cases.append({
            "displayRepresentation": {"title": text(titles[case["name"]])},
            "identifier": case.get("rawValue", case["name"]),
        })
    return {
        "assistantDefinedSchemas": [],
        "availabilityAnnotations": availability(entry),
        "cases": cases,
        "displayTypeName": text(display_name),
        "effectiveBundleIdentifiers": [],
        "fullyQualifiedTypeName": name,
        "identifier": short_name(name),
        "isSystem": False,
        "mangledTypeName": entry["mangledTypeName"],
        "mangledTypeNameByBundleIdentifier": {},
        "numericFormatTypeName": text(display_name),
        # Xcode 27 writes this for every enum, empty for an AppEnum.
        "systemProtocolMetadata": [],
        "visibilityMetadata": {"assistantOnly": False, "isDiscoverable": True},
    }


def unwrap(type_name, prefix):
    return type_name[len(prefix) + 1:-1] if type_name.startswith(prefix + "<") and type_name.endswith(">") else None


def generic_arguments(type_name):
    """The top-level generic arguments of Some.Type<A, B<C>, D>."""
    inner = type_name[type_name.index("<") + 1:type_name.rindex(">")] if "<" in type_name else ""
    parts, depth, start = [], 0, 0
    for i, ch in enumerate(inner):
        depth += ch == "<"
        depth -= ch == ">"
        if ch == "," and depth == 0:
            parts.append(inner[start:i].strip())
            start = i + 1
    if inner:
        parts.append(inner[start:].strip())
    return parts


def entity_value_type(entity):
    return {"entity": {"wrapper": {"typeName": entity["typeName"]}}}


def array_value_type(member):
    return {"array": {"wrapper": {"capabilities": 3, "memberValueType": member}}}


def enum_member(value, base_type, what):
    """The case name of `.case` (a MemberReference or Enum value)."""
    if value.get("valueKind") == "Enum":
        return value["value"]["name"]
    if value.get("valueKind") == "MemberReference" and value["value"]["baseType"] == base_type:
        return value["value"]["memberLabel"]
    raise Unsupported(f"{what}: expected .case of {base_type}")


def build_parameter(prop, enums, entities, intent):
    name = prop["label"][1:]
    what = f"{intent}.{name}"
    if prop.get("valueKind") != "InitCall":
        raise Unsupported(f"{what}: @Parameter without literal arguments")
    value_type = unwrap(prop["type"], "AppIntents.IntentParameter")
    optional = unwrap(value_type, "Swift.Optional")
    is_optional = optional is not None
    base = optional or value_type

    args = {a["label"]: a for a in prop["value"]["arguments"]}
    # Apple writes no title for the `@Parameter()` a schema macro adds to a search criteria.
    untitled = "title" not in args and base == "AppIntents.StringSearchCriteria"
    title = None if untitled else literal(args.get("title", {}), f"{what} title")
    default = args.get("default", {"valueKind": "NilLiteral"})
    # requestValueDialog is a prompt iOS shows at run time; Apple's metadata has no trace of it.
    for label, arg in args.items():
        if label not in ("title", "default", "inputConnectionBehavior", "supportedValues", "requestValueDialog") \
                and arg.get("valueKind") != "NilLiteral":
            raise Unsupported(f"{what}: argument {label} is not supported")

    dynamic_options = 0
    metadata = []
    if base == "Swift.String":
        valuetype = primitive(STRING)
        resolvable = [
            {"kindValue": 0, "valueType": primitive(STRING)},
            {"kindValue": 0, "valueType": {"array": {"wrapper": {
                "capabilities": 3, "memberValueType": primitive(2)}}}},
            {"kindValue": 0, "valueType": primitive(2)},
        ]
        if default["valueKind"] == "RawLiteral":
            metadata = [{"string": {"wrapper": default["value"]}}]
    elif base == "Swift.Bool" and not is_optional:
        valuetype = primitive(BOOL)
        resolvable = [{"kindValue": 0, "valueType": primitive(BOOL)}]
        if default["valueKind"] == "RawLiteral":
            metadata = [{"int": {"wrapper": 1 if default["value"] == "true" else 0}}]
    elif base in entities and not is_optional:
        valuetype = entity_value_type(entities[base])
        resolvable = []
        # The entity's query supplies the options.
        dynamic_options = 2
    elif base == "AppIntents.StringSearchCriteria" and not is_optional:
        valuetype = {"searchCriteria": {"wrapper": {"typeIdentifier": STRING}}}
        resolvable = []
    elif base == "Swift.Array<Swift.String>" and not is_optional:
        valuetype = array_value_type(primitive(STRING))
        resolvable = []
    elif base in enums and not is_optional:
        valuetype = {"linkEnumeration": {"wrapper": {"identifier": short_name(base)}}}
        resolvable = []
        if default["valueKind"] == "Enum":
            case = default["value"]["name"]
            raw = next((c.get("rawValue", c["name"]) for c in enums[base]["cases"] if c["name"] == case), None)
            if raw is None:
                raise Unsupported(f"{what}: default .{case} is not a case of {base}")
            metadata = [{"string": {"wrapper": raw}}]
    else:
        raise Unsupported(f"{what}: parameter type {value_type} is not supported")
    if default["valueKind"] not in ("NilLiteral", "RawLiteral", "Enum") or \
            (default["valueKind"] != "NilLiteral" and not metadata):
        raise Unsupported(f"{what}: default must be a literal")

    parameter = {
        "capabilities": 1 if metadata else 0,
        "dynamicOptionsSupport": dynamic_options,
        "inputConnectionBehavior": 0,
        "isInput": False,
        "isOptional": is_optional,
        "name": name,
        "resolvableInputTypes": resolvable,
        "typeSpecificMetadata": ["LNValueTypeSpecificMetadataKeyDefaultValue", metadata[0]] if metadata else [],
        "valueType": valuetype,
    }
    if title is not None:
        parameter["title"] = text(title)
    return parameter


def literal_list(value, what):
    """The texts of an array of string literals ([] for none)."""
    if value is None or value.get("valueKind") == "NilLiteral":
        return []
    if value.get("valueKind") != "Array":
        raise Unsupported(f"{what}: expected an array of string literals")
    return [text(literal(item, what)) for item in value["value"]]


def only_known_conformances(entry, allowed, what):
    for conformance in entry["conformances"]:
        if conformance.startswith("AppIntents.") and conformance not in allowed:
            raise Unsupported(f"{entry['typeName']}: {conformance} is not supported ({what})")


ENTITY_CONFORMANCES = {
    "AppIntents.AppEntity", "AppIntents.IndexedEntity", "AppIntents.AppValue", "AppIntents.DisplayRepresentable",
    "AppIntents.PersistentlyIdentifiable", "AppIntents.TypeDisplayRepresentable", "AppIntents._IntentValue",
    "AppIntents.InstanceDisplayRepresentable",
}
QUERY_CONFORMANCES = {
    "AppIntents.EntityQuery", "AppIntents.EntityStringQuery", "AppIntents.IndexedEntityQuery",
    "AppIntents.DynamicOptionsProvider", "AppIntents.PersistentlyIdentifiable", "AppIntents._SupportsAppDependencies",
}


def entity_property(prop, entity, entity_names):
    """One @Property(title:[indexingKey:]) of an entity, or one
    @DeferredProperty(title:), which builds an EntityProperty with an
    asyncGetter."""
    name = prop["label"][1:]
    what = f"{entity}.{name}"
    value_type = unwrap(prop["type"], "AppIntents.EntityProperty")
    optional = unwrap(value_type, "Swift.Optional")
    base = optional or value_type
    if prop.get("valueKind") != "InitCall":
        raise Unsupported(f"{what}: property type {value_type} is not supported")
    args = {a["label"]: a for a in prop["value"]["arguments"]}
    deferred = "asyncGetter" in args
    for label in args:
        if label not in (("identifier", "title", "asyncGetter") if deferred else ("title", "indexingKey")):
            raise Unsupported(f"{what}: argument {label} is not supported")
    if deferred:
        # An array of primitives or of this target's entities, loaded on demand.
        member = unwrap(base, "Swift.Array")
        if optional is not None or member is None \
                or literal(args.get("identifier", {}), f"{what} identifier") != name:
            raise Unsupported(f"{what}: a deferred property must be a non-optional array named for its identifier")
        if member in PRIMITIVES:
            member_type = primitive(PRIMITIVES[member])
        elif member in entity_names:
            member_type = entity_value_type({"typeName": short_name(member)})
        else:
            raise Unsupported(f"{what}: a deferred property of {member} is not supported")
        value = array_value_type(member_type)
    elif base in PRIMITIVES:
        value = primitive(PRIMITIVES[base])
    else:
        raise Unsupported(f"{what}: property type {value_type} is not supported")
    result = {
        # A deferred property is loaded on demand.
        "capabilities": 2 if deferred else 0,
        "identifier": name,
        "isOptional": optional is not None,
        "title": text(literal(args.get("title", {}), f"{what} title")),
        "valueType": value,
    }
    key = args.get("indexingKey")
    if key is not None:
        path = key.get("value", {}).get("components", []) if key.get("valueKind") == "KeyPath" else []
        if len(path) != 1:
            raise Unsupported(f"{what}: the indexing key must be a single CSSearchableItemAttributeSet key path")
        result["spotlightAttributeKey"] = path[0]["label"]
    return result


def transferable_types(entry):
    """The content types a Transferable entity exports, from its
    transferRepresentation { ProxyRepresentation(exporting:) ... }."""
    name = entry["typeName"]
    rep = static_property(entry, "transferRepresentation")
    if rep is None or rep.get("valueKind") != "Builder":
        raise Unsupported(f"{name}.transferRepresentation: expected a builder of representations")
    types = []
    for member in rep["value"]["members"]:
        element = member.get("element", {})
        if member.get("kind") != "buildExpression" or element.get("valueKind") != "InitCall":
            raise Unsupported(f"{name}.transferRepresentation: only plain representations are supported")
        call = element["value"]
        kind = call["type"].split("<")[0]
        args = {a["label"]: a for a in call["arguments"]}
        if kind == "CoreTransferable.ProxyRepresentation" and set(args) == {"exporting"} \
                and generic_arguments(call["type"])[1:] == ["Foundation.URL"]:
            types.append({"contentType": EXPORTED_URL})
        elif kind == "CoreTransferable.DataRepresentation" and set(args) == {"exportedContentType", "exporting"} \
                and args["exportedContentType"].get("valueKind") == "MemberReference" \
                and args["exportedContentType"]["value"]["baseType"] == "UniformTypeIdentifiers.UTType" \
                and args["exportedContentType"]["value"]["memberLabel"] in EXPORTED_PLAIN_TEXT:
            types.append({"contentType": EXPORTED_PLAIN_TEXT[args["exportedContentType"]["value"]["memberLabel"]]})
        else:
            raise Unsupported(f"{name}.transferRepresentation: {kind} with {sorted(args)} is not supported")
    return types


def build_entity(entry, entity_names):
    name = entry["typeName"]
    only_known_conformances(entry, ENTITY_CONFORMANCES, "entity")
    display = static_property(entry, "typeDisplayRepresentation")
    if display is None or display.get("valueKind") not in ("InitCall", "RawLiteral"):
        raise Unsupported(f"{name}: no literal typeDisplayRepresentation")
    alias = next((a["substitutedTypeName"] for a in entry.get("associatedTypeAliases", [])
                  if a["typeAliasName"] == "DefaultQuery"), None)
    if alias is None:
        raise Unsupported(f"{name}: no defaultQuery")
    indexed = "AppIntents.IndexedEntity" in entry["conformances"]
    protocol = [INDEXED_ENTITY, {"empty": {}}] if indexed else []
    entity = {
        "assistantDefinedSchemas": [],
        "availabilityAnnotations": availability(entry),
        "defaultQueryIdentifier": alias,
        "effectiveBundleIdentifiers": [],
        # Xcode 27 writes these for every entity.
        "entitySyncMetadata": {"entitySyncType": 0},
        "fullyQualifiedTypeName": name,
        "mangledTypeName": entry["mangledTypeName"],
        "mangledTypeNameByBundleIdentifier": {},
        "properties": [entity_property(p, name, entity_names) for p in entry.get("properties", [])
                       if p["label"].startswith("_") and p["type"].startswith("AppIntents.EntityProperty<")],
        "requiredCapabilities": [],
        "systemProtocolMetadata": protocol,
        "systemProtocolMetadataV2": protocol,
        "transient": False,
        "typeName": short_name(name),
        "typeSpecificMetadata": [],
        "visibilityMetadata": {"assistantOnly": False, "isDiscoverable": True},
    }
    if display["valueKind"] == "RawLiteral":
        # A name alone: Apple writes no numeric format or synonyms for it.
        entity["displayTypeName"] = text(display["value"])
    else:
        args = {a["label"]: a for a in display["value"]["arguments"]}
        for label in args:
            if label not in ("name", "numericFormat", "synonyms"):
                raise Unsupported(f"{name}.typeDisplayRepresentation: argument {label} is not supported")
        if "numericFormat" not in args:
            raise Unsupported(f"{name}.typeDisplayRepresentation: a numericFormat is required")

        def count(segment):
            if segment.get("valueKind") == "Enum" and segment["value"]["name"] == "int":
                return "int"
            raise Unsupported(f"{name}.typeDisplayRepresentation: numericFormat may only interpolate .int")

        numeric, _ = interpolated(args["numericFormat"], f"{name} numericFormat", count)
        entity["displayTypeName"] = text(literal(args["name"], f"{name} name"))
        entity["numericFormatTypeName"] = text(numeric)
        entity["synonyms"] = literal_list(args.get("synonyms"), f"{name} synonyms")
    # An entity that isn't Transferable has no transferableContentTypes at all.
    if "CoreTransferable.Transferable" in entry["conformances"]:
        entity["transferableContentTypes"] = {"exportableTypes": transferable_types(entry), "importableTypes": []}
    return entity


def build_query(entry, entities, default_queries):
    name = entry["typeName"]
    only_known_conformances(entry, QUERY_CONFORMANCES, "entity query")
    if "AppIntents.EntityStringQuery" not in entry["conformances"]:
        raise Unsupported(f"{name}: only EntityStringQuery queries are supported")
    entity = next((a["substitutedTypeName"] for a in entry.get("associatedTypeAliases", [])
                   if a["typeAliasName"] == "Entity"), None)
    if entity not in entities:
        raise Unsupported(f"{name}: {entity} is not an entity of this target")
    return {
        "availabilityAnnotations": availability(entry),
        # EntityQuery's identifiers, string search and suggestions, plus
        # Spotlight lookup for an IndexedEntityQuery.
        "capabilities": 70 | (256 if "AppIntents.IndexedEntityQuery" in entry["conformances"] else 0),
        "defaultQueryForEntity": name in default_queries,
        "effectiveBundleIdentifiers": [],
        "entityType": short_name(entity),
        "fullyQualifiedIdentifier": name,
        "identifier": short_name(name),
        "mangledTypeName": entry["mangledTypeName"],
        "mangledTypeNameByBundleIdentifier": {},
        "parameters": [],
        "queryType": short_name(name),
        "resultValueType": entity_value_type(entities[entity]),
        "sortingOptions": [],
        "visibilityMetadata": {"assistantOnly": False, "isDiscoverable": True},
    }


def interpolated(value, what, placeholder):
    """The text of an interpolated string literal, with each interpolation
    replaced by placeholder(segment) (which returns its name, or raises)."""
    if value.get("valueKind") == "RawLiteral":
        return value["value"], []
    if value.get("valueKind") != "InterpolatedStringLiteral":
        raise Unsupported(f"{what}: expected a string literal, got {value.get('valueKind')}")
    out, names = "", []
    for segment in value["value"]["segments"]:
        if segment.get("valueKind") == "RawLiteral":
            out += segment["value"]
        else:
            name = placeholder(segment)
            out += "${" + name + "}"
            names.append(name)
    return out, names


def action_summary(entry, parameters):
    """actionConfiguration for a static parameterSummary of the form
    Summary("... \\(\\.$parameter) ..."), the only form supported."""
    name = entry["typeName"]
    summary = static_property(entry, "parameterSummary")
    if summary is None:
        return None
    if summary.get("valueKind") != "InitCall" or \
            not summary["value"]["type"].startswith("AppIntents.IntentParameterSummary<"):
        raise Unsupported(f"{name}.parameterSummary: only Summary(\"...\") is supported")
    args = summary["value"]["arguments"]
    for extra in args[1:]:
        if extra.get("valueKind") != "NilLiteral":
            raise Unsupported(f"{name}.parameterSummary: argument {extra.get('label')} is not supported")

    def parameter(segment):
        if segment.get("valueKind") != "KeyPath":
            raise Unsupported(f"{name}.parameterSummary: only \\.$parameter interpolations are supported")
        return segment["value"]["path"].lstrip("$")

    format_string, used = interpolated(args[0], f"{name}.parameterSummary", parameter)
    names = [p["name"] for p in parameters]
    if any(n not in names for n in used) or sorted(used) != sorted(names):
        raise Unsupported(f"{name}.parameterSummary: must show every parameter exactly once")
    return {"actionSummary": {"wrapper": {
        "otherParameterIdentifiers": [],
        "summaryString": {"formatString": format_string, "parameterIdentifiers": used},
    }}}


# The system intents: the protocol, what iOS records for it, and its
# metadata. OpenIntent and ShowInAppSearchResultsIntent open the app whether
# or not the intent says so.
SEARCH_SCOPES = {"general": "general"}


def assistant_schema(entry):
    """The assistant schema an intent declares through `__appSchemaIntent`
    (what @AppIntent(schema:) expands to) as assistantDefinedSchemas lists
    it, or None for an intent without one."""
    name = entry["typeName"]
    conformances = entry["conformances"]
    declared = static_property(entry, "__appSchemaIntent")
    if declared is None and "AppIntents.AssistantSchemaIntent" not in conformances \
            and "AppIntents.AssistantIntent" not in conformances:
        return None
    if declared is None or declared.get("valueKind") != "RawLiteral" \
            or "AppIntents.AssistantSchemaIntent" not in conformances \
            or "AppIntents.AssistantIntent" not in conformances:
        raise Unsupported(f"{name}: an assistant schema needs AssistantSchemaIntent and a literal __appSchemaIntent")
    if declared["value"] not in ASSISTANT_SCHEMAS:
        raise Unsupported(f"{name}: assistant schema {declared['value']} is not supported "
                          f"(only {sorted(ASSISTANT_SCHEMAS)})")
    schema, protocol = ASSISTANT_SCHEMAS[declared["value"]]
    if protocol not in conformances:
        raise Unsupported(f"{name}: assistant schema {declared['value']} needs {protocol}")
    return {"domain": declared["value"].split(".")[0], "name": schema, "version": "1.0.0"}


def system_protocol(entry, widget):
    """(systemProtocols, systemProtocolMetadata) of an intent, in the order
    the intent conforms to them."""
    name = entry["typeName"]
    conformances = entry["conformances"]
    found = []
    if widget:
        found.append(("AppIntents.WidgetConfigurationIntent", WIDGET_CONFIGURATION, {"empty": {}}))
    if "AppIntents.OpenIntent" in conformances:
        found.append(("AppIntents.OpenIntent", OPEN_ENTITY, {"empty": {}}))
    if "AppIntents.SnippetIntent" in conformances:
        found.append(("AppIntents.SnippetIntent", SNIPPET, {"empty": {}}))
    if "AppIntents.ShowInAppSearchResultsIntent" in conformances:
        scopes = static_property(entry, "searchScopes")
        if scopes is None or scopes.get("valueKind") != "Array":
            raise Unsupported(f"{name}: searchScopes must be a literal array")
        names = [enum_member(item, "AppIntents.StringSearchScope", f"{name}.searchScopes") for item in scopes["value"]]
        if not names or any(n not in SEARCH_SCOPES for n in names):
            raise Unsupported(f"{name}.searchScopes: only {sorted(SEARCH_SCOPES)} is supported")
        found.append(("AppIntents.ShowInAppSearchResultsIntent", SHOW_IN_APP_SEARCH,
                      {"showInAppStringSearchResults": {"searchScopes": [SEARCH_SCOPES[n] for n in names]}}))
    if len(found) > 1:
        raise Unsupported(f"{name}: more than one system intent is not supported")
    if assistant_schema(entry):
        found.append(("AppIntents.AssistantIntent", ASSISTANT_INTENT, {"empty": {}}))
    found.sort(key=lambda item: conformances.index(item[0]))
    return [protocol for _, protocol, _ in found], [part for _, protocol, metadata in found for part in (protocol, metadata)]


# What perform() may return: the flags each part of its result sets.
OUTPUT_FLAGS = {
    "AppIntents.IntentResult": 0,
    "AppIntents.ProvidesDialog": 4,
    "AppIntents.ShowsSnippetView": 2,
    "AppIntents.ShowsSnippetIntent": 32,
}


def perform_result(name, result, widget, entities):
    """(outputFlags, outputType or None) for a PerformResult type."""
    # A widget configuration intent never runs.
    if result == "Swift.Never" and widget:
        return 8, None
    if widget or not (result or "").startswith("some "):
        raise Unsupported(f"{name}: perform() returning {result} is not supported")
    flags, output = 0, None
    for part in result[len("some "):].split(" & "):
        returned = unwrap(part, "AppIntents.ReturnsValue")
        if returned == "Swift.String":
            output = primitive(STRING)
        elif returned is not None and unwrap(returned, "Swift.Array") in entities:
            output = array_value_type(entity_value_type(entities[unwrap(returned, "Swift.Array")]))
        elif returned is not None:
            raise Unsupported(f"{name}: perform() returning a value of {returned} is not supported")
        elif part in OUTPUT_FLAGS:
            flags += OUTPUT_FLAGS[part]
        else:
            raise Unsupported(f"{name}: perform() returning {part} is not supported")
    return flags, output


def build_intent(entry, enums, entities):
    name = entry["typeName"]
    widget = "AppIntents.WidgetConfigurationIntent" in entry["conformances"]
    result = next((a["substitutedTypeName"] for a in entry.get("associatedTypeAliases", [])
                   if a["typeAliasName"] == "PerformResult"), None)
    output_flags, output_type = perform_result(name, result, widget, entities)
    for supported in entry["conformances"]:
        if supported.startswith("AppIntents.") and supported not in (
                "AppIntents.AppIntent", "AppIntents.WidgetConfigurationIntent",
                "AppIntents.PersistentlyIdentifiable", "AppIntents._SupportsAppDependencies",
                "AppIntents.SystemIntent", "AppIntents.OpenIntent", "AppIntents.ShowInAppSearchResultsIntent",
                "AppIntents.SnippetIntent", "AppIntents.AssistantSchemaIntent", "AppIntents.AssistantIntent"):
            raise Unsupported(f"{name}: {supported} is not supported")
    title = static_property(entry, "title")
    if title is None:
        raise Unsupported(f"{name}: no literal title")
    description = static_property(entry, "description")
    open_app = static_property(entry, "openAppWhenRun")
    if open_app is not None and open_app.get("valueKind") != "RawLiteral":
        raise Unsupported(f"{name}.openAppWhenRun: expected a literal")
    schema = assistant_schema(entry)
    protocols, protocol = system_protocol(entry, widget)
    opens_app = open_app["value"] == "true" if open_app is not None else \
        bool({"AppIntents.OpenIntent", "AppIntents.ShowInAppSearchResultsIntent"} & set(entry["conformances"]))
    # 1 runs in the background, 2 in the foreground.
    modes = static_property(entry, "supportedModes")
    if modes is None:
        supported_modes = 2 if opens_app else 1
    else:
        case = enum_member(modes, "AppIntents.IntentModes", f"{name}.supportedModes")
        if case not in ("foreground", "background") or (case == "foreground") != opens_app:
            raise Unsupported(f"{name}.supportedModes: .{case} with openAppWhenRun {opens_app} is not supported")
        supported_modes = 2 if case == "foreground" else 1
    targets = static_property(entry, "allowedExecutionTargets")
    if targets is not None and enum_member(targets, "AppIntents.IntentExecutionTargets", name) != "main":
        raise Unsupported(f"{name}.allowedExecutionTargets: only .main is supported")
    discoverable = static_property(entry, "isDiscoverable")
    if discoverable is not None and discoverable.get("valueKind") != "RawLiteral":
        raise Unsupported(f"{name}.isDiscoverable: expected a literal")
    parameters = [build_parameter(p, enums, entities, name) for p in entry.get("properties", [])
                  if p["label"].startswith("_") and p["type"].startswith("AppIntents.IntentParameter<")]
    visible = discoverable["value"] == "true" if discoverable is not None else True
    keywords = []
    description_text = None
    if description is not None and description.get("valueKind") == "InitCall":
        args = {a["label"]: a for a in description["value"]["arguments"]}
        if args.get("categoryName", {"valueKind": "NilLiteral"}).get("valueKind") != "NilLiteral" \
                or set(args) - {"", "categoryName", "searchKeywords"}:
            raise Unsupported(f"{name}.description: only the text and searchKeywords are supported")
        keywords = literal_list(args.get("searchKeywords"), f"{name}.description searchKeywords")
        description_text = text(literal(args[""], f"{name}.description"))
    elif description is not None:
        description_text = text(literal(description, f"{name}.description"))
    action = {
        "assistantDefinedSchemaTraits": [],
        "assistantDefinedSchemas": [schema] if schema else [],
        "authenticationPolicy": 0,
        "availabilityAnnotations": availability(entry),
        "effectiveBundleIdentifiers": [],
        "fullyQualifiedTypeName": name,
        "identifier": short_name(name),
        "isAuthPolExplicit": False,
        "isDiscoverable": visible and not widget,
        "mangledTypeName": entry["mangledTypeName"],
        "mangledTypeNameByBundleIdentifier": {},
        "mangledTypeNameByBundleIdentifierV2": {},
        "mangledTypeNameV2": entry["mangledTypeName"],
        "openAppWhenRun": opens_app,
        "outputFlags": output_flags,
        "parameters": parameters,
        "presentationStyle": 0,
        "requiredCapabilities": [],
        "supportedModes": supported_modes,
        "systemProtocolMetadata": protocol,
        "systemProtocolMetadataV2": protocol,
        "systemProtocols": protocols,
        "title": text(literal(title, f"{name}.title")),
        "typeSpecificMetadata": [],
        "visibilityMetadata": {"assistantOnly": False, "isDiscoverable": visible},
    }
    if targets is not None:
        action["allowedTargets"] = [{"type": 1}]
    # An intent without a description has no descriptionMetadata at all.
    if description_text is not None:
        action["descriptionMetadata"] = {"descriptionText": description_text, "searchKeywords": keywords}
    if output_type is not None:
        action["outputType"] = output_type
    if "AppIntents.OpenIntent" in entry["conformances"]:
        # The entity opened, described again in full.
        value = next((a["substitutedTypeName"] for a in entry.get("associatedTypeAliases", [])
                      if a["typeAliasName"] == "Value"), None)
        if value not in entities:
            raise Unsupported(f"{name}: opens {value}, which is not an entity of this target")
        action["typeSpecificMetadata"] = [
            "LNActionTypeMetadataKeyEntityMetadata", {"entityMetadata": {"wrapper": entities[value]}},
            "LNActionTypeMetadataKeyEntityType", {"string": {"wrapper": short_name(value)}},
        ]
    summary = action_summary(entry, parameters)
    if summary:
        action["actionConfiguration"] = summary
    return action


def build_shortcuts(entry, actions):
    """autoShortcuts from an AppShortcutsProvider's literal appShortcuts:
    AppShortcut(intent: SomeIntent(), phrases: [...], shortTitle:,
    systemImageName:), with phrases that only interpolate the app name."""
    name = entry["typeName"]
    prop = static_property(entry, "appShortcuts")
    if prop is None or prop.get("valueKind") != "Builder":
        raise Unsupported(f"{name}: appShortcuts must be a literal list of AppShortcut(...)")
    shortcuts = []
    for member in prop["value"]["members"]:
        element = member.get("element", {})
        if member.get("kind") != "buildExpression" or element.get("valueKind") != "InitCall" \
                or element["value"]["type"] != "AppIntents.AppShortcut":
            raise Unsupported(f"{name}.appShortcuts: only AppShortcut(...) entries are supported")
        args = {a["label"]: a for a in element["value"]["arguments"]}
        intent = args.get("intent", {})
        if intent.get("valueKind") != "InitCall" or intent["value"]["arguments"]:
            raise Unsupported(f"{name}.appShortcuts: the intent must be created without arguments")
        identifier = short_name(intent["value"]["type"])
        if identifier not in actions:
            raise Unsupported(f"{name}.appShortcuts: {identifier} is not an intent in this target")
        if set(args) - {"intent", "phrases", "shortTitle", "systemImageName"}:
            raise Unsupported(f"{name}.appShortcuts: arguments {sorted(set(args))} are not supported")

        def app_name(segment):
            if segment.get("valueKind") == "Enum" and segment["value"]["name"] == "applicationName":
                return "applicationName"
            raise Unsupported(f"{name}.appShortcuts: phrases may only interpolate .applicationName")

        phrases = [text(interpolated(p, f"{name} phrase", app_name)[0]) for p in args["phrases"]["value"]]
        shortcuts.append({
            "actionIdentifier": identifier,
            "availabilityAnnotations": availability(entry),
            "phraseTemplates": phrases,
            "shortTitle": text(literal(args["shortTitle"], f"{name} shortTitle")),
            "systemImageName": literal(args["systemImageName"], f"{name} systemImageName"),
        })
    return shortcuts


def generate(entries):
    enum_entries = {e["typeName"]: e for e in entries
                    if e["kind"] == "enum" and "AppIntents.AppEnum" in e["conformances"]}
    entity_entries = [e for e in entries if "AppIntents.AppEntity" in e["conformances"]]
    entity_names = {e["typeName"] for e in entity_entries}
    entities = {e["typeName"]: build_entity(e, entity_names) for e in entity_entries}
    default_queries = {e["defaultQueryIdentifier"] for e in entities.values()}
    queries = {}
    for entry in entries:
        if "AppIntents.EntityQuery" in entry["conformances"]:
            query = build_query(entry, entities, default_queries)
            queries[query["identifier"]] = query
    actions = {}
    for entry in entries:
        if "AppIntents.AppIntent" in entry["conformances"]:
            action = build_intent(entry, enum_entries, entities)
            actions[action["identifier"]] = action
    enums = [build_enum(e) for e in enum_entries.values()]
    providers = [e for e in entries if "AppIntents.AppShortcutsProvider" in e["conformances"]]
    if len(providers) > 1:
        raise Unsupported("more than one AppShortcutsProvider")
    metadata = {
        "actions": actions,
        "assistantEntities": [],
        "assistantIntentNegativePhrases": [],
        "assistantIntents": [],
        "autoShortcuts": build_shortcuts(providers[0], actions) if providers else [],
        "entities": {e["typeName"]: e for e in entities.values()},
        "enums": enums,
        "generator": {"name": "xcode-tools", "version": TOOLS_VERSION},
        "negativePhrases": [],
        "queries": queries,
        "shortcutTileColor": 14,
        "version": 1,
    }
    if providers:
        metadata["autoShortcutProviderMangledName"] = providers[0]["mangledTypeName"]
    return metadata


def write(out, metadata):
    out.mkdir(parents=True, exist_ok=True)
    (out / "extract.actionsdata").write_text(
        json.dumps(metadata, sort_keys=True, separators=(",", ":"), ensure_ascii=False))
    (out / "version.json").write_text(
        '{\n  "version" : "3.0",\n  "toolsVersion" : "%s"\n}' % TOOLS_VERSION)


def load(paths):
    entries = []
    for path in paths:
        entries.extend(json.loads(Path(path).read_text()))
    return entries


def normalized(metadata):
    """Apple's processor orders the enums, each parameter's
    resolvableInputTypes, the key/value pairs of an action's
    typeSpecificMetadata and an intent's system protocols (with their
    metadata pairs) arbitrarily: they are sets, and two runs on the same
    input differ. Compare them sorted."""
    copy = json.loads(json.dumps(metadata))
    copy["enums"] = sorted(copy["enums"], key=lambda e: e["identifier"])
    for action in copy["actions"].values():
        for parameter in action["parameters"]:
            parameter["resolvableInputTypes"].sort(key=lambda t: json.dumps(t, sort_keys=True))
        pairs = sorted(zip(action["typeSpecificMetadata"][::2], action["typeSpecificMetadata"][1::2]))
        action["typeSpecificMetadata"] = [item for pair in pairs for item in pair]
        if "systemProtocols" in action:
            action["systemProtocols"].sort()
        for key in ("systemProtocolMetadata", "systemProtocolMetadataV2"):
            if key in action:
                pairs = sorted(zip(action[key][::2], action[key][1::2]), key=lambda p: p[0])
                action[key] = [item for pair in pairs for item in pair]
    return copy


def refusals():
    """Changes to a target's const values that the generator must refuse
    (name -> a function applying the change to a copy of the entries, which
    raises LookupError when the target has no type to change), so that
    anything it cannot match to Apple's output stays an error."""
    def find(copy, name):
        found = next((e for e in copy if e["typeName"].endswith("." + name)), None)
        if found is None:
            raise LookupError(name)
        return found

    def conforming(copy, protocol):
        found = next((e for e in copy if protocol in e["conformances"]), None)
        if found is None:
            raise LookupError(protocol)
        return found

    def having(copy, label):
        found = next((e for e in copy if any(p["label"] == label for p in e.get("properties", []))), None)
        if found is None:
            raise LookupError(label)
        return found

    def prop(entry, label, static=True):
        found = next((p for p in entry["properties"] if p["label"] == label and (p["isStatic"] == "true") == static), None)
        if found is None:
            raise LookupError(label)
        return found

    def result(entry, value):
        for alias in entry["associatedTypeAliases"]:
            if alias["typeAliasName"] == "PerformResult":
                alias["substitutedTypeName"] = value

    def drop_argument(entry, label, static, argument):
        value = prop(entry, label, static)["value"]
        value["arguments"] = [a for a in value["arguments"] if a["label"] != argument]

    def schema_intent(copy, schema):
        found = next((e for e in copy if any(p["label"] == "__appSchemaIntent" and p["value"] == schema
                                             for p in e.get("properties", []))), None)
        if found is None:
            raise LookupError(schema)
        return found

    return {
        "an entity conforming to FileEntity": lambda c: conforming(c, "AppIntents.AppEntity")["conformances"].append("AppIntents.FileEntity"),
        "an entity without a numeric format": lambda c: drop_argument(find(c, "PhoebusPostEntity"), "typeDisplayRepresentation", True, "numericFormat"),
        "a property of an unsupported type": lambda c: prop(find(c, "PhoebusPostEntity"), "_score", False).update(type="AppIntents.EntityProperty<Swift.Double>"),
        "a deferred property of an unsupported type": lambda c: prop(having(c, "_loadedComments"), "_loadedComments", False).update(
            type="AppIntents.EntityProperty<Swift.Array<Swift.Double>>"),
        "an optional deferred property": lambda c: prop(having(c, "_loadedComments"), "_loadedComments", False).update(
            type="AppIntents.EntityProperty<Swift.Optional<Swift.Array<Swift.String>>>"),
        "a query that doesn't take strings": lambda c: conforming(c, "AppIntents.EntityQuery")["conformances"].remove("AppIntents.EntityStringQuery"),
        "an enumerable query": lambda c: conforming(c, "AppIntents.EntityQuery")["conformances"].append("AppIntents.EnumerableEntityQuery"),
        "a second system intent": lambda c: conforming(c, "AppIntents.OpenIntent")["conformances"].append("AppIntents.SnippetIntent"),
        "a delete intent": lambda c: conforming(c, "AppIntents.OpenIntent")["conformances"].append("AppIntents.DeleteIntent"),
        "an assistant schema it doesn't know": lambda c: prop(schema_intent(c, "system.open"), "__appSchemaIntent").update(value="system.create"),
        "an assistant schema without its system intent": lambda c: schema_intent(c, "system.open")["conformances"].remove("AppIntents.OpenIntent"),
        "an assistant schema of another system intent": lambda c: prop(schema_intent(c, "system.open"), "__appSchemaIntent").update(value="system.searchInApp"),
        "an assistant intent without a schema": lambda c: schema_intent(c, "system.open").update(
            properties=[p for p in schema_intent(c, "system.open")["properties"] if p["label"] != "__appSchemaIntent"]),
        "a perform() that opens an intent": lambda c: result(find(c, "FindIndexedPhoebusPostsIntent"), "some AppIntents.OpensIntent"),
        "a perform() returning another value": lambda c: result(find(c, "PhoebusContentIndexStatusIntent"), "some AppIntents.ReturnsValue<Swift.Int>"),
        "a search scope that isn't general": lambda c: prop(conforming(c, "AppIntents.ShowInAppSearchResultsIntent"), "searchScopes")["value"][0]["value"].update(name="messages"),
        "a background intent that opens the app": lambda c: find(c, "SetPhoebusContentIndexingIntent").update(
            properties=find(c, "SetPhoebusContentIndexingIntent")["properties"] + [
                {"label": "openAppWhenRun", "type": "Swift.Bool", "isStatic": "true", "valueKind": "RawLiteral", "value": "true"}]),
        "a parameter option the metadata has no field for": lambda c: prop(find(c, "SetPhoebusContentIndexingIntent"), "_enabled", False)["value"]["arguments"].append(
            {"label": "inputOptions", "type": "x", "valueKind": "RawLiteral", "value": "y"}),
    }


def compare(root, diff_lines):
    """Compares the generator with Apple's output for each fixture under
    root."""
    for fixtures in sorted(p for p in root.iterdir() if p.is_dir()):
        expected = json.loads((fixtures / "Metadata.appintents/extract.actionsdata").read_text())
        actual = generate(load([fixtures / "input.swiftconstvalues"]))
        # Apple writes its two keys in either order.
        version = json.loads((fixtures / "Metadata.appintents/version.json").read_text())
        if normalized(actual) != normalized(expected):
            a = json.dumps(normalized(expected), sort_keys=True, indent=1).splitlines()
            b = json.dumps(normalized(actual), sort_keys=True, indent=1).splitlines()
            import difflib
            print("\n".join(list(difflib.unified_diff(a, b, "apple", "generated", lineterm=""))[:diff_lines]))
            sys.exit(f"appintents-metadata: output differs from Apple's for {fixtures.name}")
        if version != {"version": "3.0", "toolsVersion": TOOLS_VERSION}:
            sys.exit(f"appintents-metadata: version.json differs from Apple's for {fixtures.name}: "
                     f"{version} (the generator writes toolsVersion {TOOLS_VERSION})")
        print(f"appintents-metadata: {fixtures.name} matches Apple's output "
              f"({len(actual['actions'])} intents, {len(actual['enums'])} enums, "
              f"{len(actual['entities'])} entities, {len(actual['queries'])} queries, "
              f"{len(actual['autoShortcuts'])} app shortcuts)")


def self_test():
    root = Path(__file__).resolve().parent.parent / "Tests/Fixtures/AppIntents"
    compare(root, 60)
    # Every change in refusals() must be refused wherever the fixture has the
    # type it changes, and by at least one fixture.
    tried = set()
    for fixtures in sorted(p for p in root.iterdir() if p.is_dir()):
        entries = load([fixtures / "input.swiftconstvalues"])
        for what, change in refusals().items():
            changed = copy.deepcopy(entries)
            try:
                change(changed)
            except LookupError:
                continue
            tried.add(what)
            try:
                generate(changed)
            except Unsupported:
                continue
            sys.exit(f"appintents-metadata: {what} was accepted, not refused ({fixtures.name})")
    untried = sorted(set(refusals()) - tried)
    if untried:
        sys.exit(f"appintents-metadata: no fixture has the types to try refusing: {', '.join(untried)}")
    print(f"appintents-metadata: {len(tried)} changes to the const values are refused")


def main():
    args = sys.argv[1:]
    if args == ["--self-test"]:
        return self_test()
    if len(args) == 2 and args[0] == "--compare":
        return compare(Path(args[1]), 400)
    if len(args) < 2:
        sys.exit(__doc__.strip().splitlines()[2])
    try:
        metadata = generate(load(args[1:]))
    except Unsupported as error:
        sys.exit(f"appintents-metadata: {error}")
    write(Path(args[0]), metadata)
    print(f"{args[0]}: {len(metadata['actions'])} intents, {len(metadata['enums'])} enums")


if __name__ == "__main__":
    main()
