// GENERATED by scripts/generate/gen-settings-search-index.py - do not edit by hand.
//
// Crawled from the settings screen sources so the index cannot drift from
// the screens.

extension SettingsSearch {
    /// Every searchable settings row, in tap order from the root.
    public static let index: [SettingsSearchEntry] = [
        SettingsSearchEntry(title: "Buy Us a Coffee", breadcrumb: "Settings", screen: .settingsRoot, rowTitle: "Buy Us a Coffee"),
    ]
}
